import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube
} from 'react-icons/ai';
import Image from 'next/image';
import bjoern from '../public/bjoern.png';
import en from '../public/en.svg'
import no from '../public/no.svg'
import ce from '../public/certificate.svg'
import py from '../public/python.svg'
import re from '../public/react-icon.svg'
import ja from '../public/javascript.svg'
import ta from '../public/tailwind.svg'
import ht from '../public/html5.svg'
import cs from '../public/css3.svg'
import { useState } from 'react';
import { Menu } from "@headlessui/react"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? 'dark': ""}>
      <Head>
        <title>Bjoern Andre Portfolio</title>
        <meta charSet='utf-8'/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Garosath</h1>
            <ul className='flex items-center'>
              <li className='cursor-pointer'>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='"cursor-pointer text-2xl dark:text-white'/>
              </li>
              <li>
                
              </li>
              <Menu as="li">
                <Menu.Button className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Language</Menu.Button>
                <Menu.Items>
                  <Menu.Item>
                    {({ active }) => (
                      <a href='#' className={'flex items-center px-4 py-2 text-sm ${active ? "bg-indigo-500 text-white": "text-gray-700"}'}>Test
                      </a>
                    )}
                  </Menu.Item>
                </Menu.Items>
              </Menu>
            </ul>
          </nav>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={bjoern} layout='fill' objectFit='cover' alt="Drawing of Bjoern" />
          </div>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Bjoern André</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer & Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>
              Student providing services for programming and design content needs.
            </p>
          </div>
          <div className='text-5xl pb-10 flex justify-center gap-16 py-3 text-gray-600 dark:text-white'>
            <a><AiFillTwitterCircle /></a>
            <a><AiFillLinkedin /></a>
            <a><AiFillYoutube /></a>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl md:text-4xl py-1 dark:text-white'>Background</h3>
            <p className='text-md py-2 md:text-xl leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet, consectetur <span className=' text-teal-500'>adipiscing</span> elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-white font-extrabold text-center m-5'>Skillset</h3>
          <div className='lg:flex flex-wrap gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 max-w-xs min-w-sm mx-auto dark:bg-white'>
              <h3 className='text-xl md:text-2xl font-black pb-5'>Python</h3>
              <div className='relative justify-center mx-auto w-40 h-40 md:w-30 md:h-30 overflow-hidden'>
                <Image src={py} alt="Python icon" />
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 max-w-xs min-w-sm mx-auto dark:bg-white'>
              <h3 className='text-xl md:text-2xl font-black pb-5'>HTML5</h3>
              <div className='relative justify-center mx-auto w-40 h-40 md:w-30 md:h-30 overflow-hidden'>
                <Image src={ht} alt="Python icon" />
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 max-w-xs min-w-sm mx-auto dark:bg-white'>
              <h3 className='text-xl md:text-2xl font-black pb-5'>CSS3</h3>
              <div className='relative justify-center mx-auto w-40 h-40 md:w-30 md:h-30 overflow-hidden'>
                <Image src={cs} alt="Python icon" />
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 max-w-xs min-w-sm mx-auto dark:bg-white'>
              <h3 className='text-xl md:text-2xl font-black pb-5'>Javascript</h3>
              <div className='relative justify-center mx-auto w-40 h-40 md:w-30 md:h-30 overflow-hidden'>
                <Image src={ja} alt="Javascript icon" />
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 max-w-xs min-w-sm mx-auto dark:bg-white'>
              <h3 className='text-xl md:text-2xl font-black pb-5'>React</h3>
              <div className='relative justify-center mx-auto w-40 h-40 md:w-30 md:h-30 overflow-hidden'>
                <Image src={re} layout='fill' alt="React icon" />
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 max-w-xs min-w-sm mx-auto dark:bg-white'>
              <h3 className='text-xl md:text-2xl font-black pb-5'>Tailwind CSS</h3>
              <div className='relative justify-center mx-auto w-40 h-40 md:w-30 md:h-30 overflow-hidden'>
                <Image src={ta} layout='fill' alt="React icon" />
              </div>
            </div>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 max-w-md mx-auto dark:bg-white'>
              <h3 className='text-xl md:text-2xl font-black p-5'>Additional expertise</h3>
              <ul className='list-disc'>
                <li>Arduino</li>
                <li>Networking</li>
                <li>Server management</li>
                <li>Sony Vegas</li>
                <li>Photoshop</li>
                </ul>
            </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 max-w-md mx-auto dark:bg-white'>
              <div className='relative justify-center mx-auto w-40 h-40 md:w-30 md:h-30 overflow-hidden'>
              <Image src={ce} alt="Certificate stock image" />
              </div>
              <h3 className='text-xl md:text-2xl font-black p-5'>Certifications</h3>
              <ul className='list-disc'>
                <li>Certificate of apprenticeship in Computer & Electronics</li>
                <li>Bachelors degree in Information Science</li>
                </ul>
            </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portofolio</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              Student providing services for programming and design content needs.
            </p>
          </div>
          <div>
            <div>
              
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
